version: '2'

services:
  mysql:
    restart: on-failure
    image: amacharla/psst-db
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=url_db
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  psst:
    restart: always
    image: amacharla/psst
    container_name: urlshortener
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./web_app:/var/www/url_shortener/web_app
    ports:
      - "80:80"
